### ISSUE TITLE
Add steps to run Client in localhost 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#11]
The client has a gatsby starter in it. Add a readme.md add the steps to install node, gatsby cli, port running, and all other pre-requisites. 

Refer: https://github.com/youandesign/youandesign

**Comment by kumarshantanu01** [comment]
@Aniket762 , I would like to work on it.

**Comment by Aniket762** [comment]
Sure @kumarshantanu01 go for it.  Create the readme  `client/readme.md`
