### ISSUE TITLE
Add hacktoberfest banner and ways to contribute

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#2]
Please follow https://github.com/Aniket762/webwiz-portfolio

Make sure to write the steps for setting up the local env to run the software

**Comment by rakeshprask** [comment]
Hello @Aniket762 Can you assign me this issue ? I'd like to work on this.

**Comment by sumana2001** [comment]
I am interested. Please assign it to me

**Comment by Neeraj2002** [comment]
I would like to work on this issue!
