### ISSUE TITLE
Home Screen overflowing

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#21]
The home screen of the application is overflowing when dragged up. While scrolling up it is crossing the safe area, add Safearea widget to stop the overflow. You can find the code in `lib`

As it is a frontend issue please attach gifs or screenshots to show the bug is resolved.

**Comment by AryanKhubchandani** [comment]
Hey @Aniket762! Can I work on this issue?

**Comment by Aniket762** [comment]
> Hey @Aniket762! Can I work on this issue?

Sure thing go for it 😎
