### ISSUE TITLE
Configure Auth with JWT

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#23]
Create an authentication system for admins to log in. Please note we are not letting users signup or register we would be generating passwords from the backend, forgot password, change in the email will be handled manually won't be tedious because we would have at max 3 admins. 

You just need to create the login authentication using JWT and test the APIs using postman would be fine. The front end is being developed as of now #19. 

Make a directory in `backend` as `auth` and write the script finally do a single function call in `backend/lib/server.js`

All you need to take from the user is:
```
Email: String
Password: String
```
Reference: https://www.digitalocean.com/community/tutorials/nodejs-jwt-expressjs 

Although not a compulsion, if possible do add gifs or screenshots to show the Postman testing of the APIs. 

Please do star the repo to increase visibility and help us reach a bigger audience because this project is ours as much as yours😁⭐️

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this?

**Comment by Kishore-abhimanyu** [comment]
@Aniket762 Could you please review the pull request and merge it?
