### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#27]
Add a splash screen for the flutter app and keep it for 5 seconds. All you need to do is center the logo with a black screen and below that write `Achieve`

You can find the logo `assets\achieve.png`

Resource: https://flutter.dev/docs/development/ui/advanced/splash-screen

**Comment by ShreyaKhetan765** [comment]
hey @Aniket762 I would like to work on this. Please assign it to me.

**Comment by rajoriaakash** [comment]
Still open for grabs?💀

**Comment by rajoriaakash** [comment]
Hi, @Aniket762 I just created a PR #28 for this issue.
Please review it, Thanks :)

**Comment by rajoriaakash** [comment]
Also, I might have a little favour to ask you. :)
Since this app is missing an app icon I can add its logo to the app icon in a new separate issue.
Could you create that issue and mark it "hacktoberfest" since I'm still 2 PR's behind and its the last day 😔
I would be glad :)

**Comment by Aniket762** [comment]
> Also, I might have a little favour to ask you. :) Since this app is missing an app icon I can add its logo to the app icon in a new separate issue. Could you create that issue and mark it "hacktoberfest" since I'm still 2 PR's behind and its the last day 😔 I would be glad :)

Sure would do that for you.  You find the logo in `assets/achieve.png`  add the app icon and name and send the PR. You can create the issue yourself while closing your PR I would add the tag of hacktobefest and that would do!
