### ISSUE TITLE
Change App Icon

### ISSUE THREAD

**Issue by rajoriaakash** [betaoverflow/achieve#29]
Change the app icon from flutter default to the "achieve" logo.

**Comment by rajoriaakash** [comment]
Hi @Aniket762 , created this issue.
Please mark it for hacktoberfest.Thanks :)

**Comment by rajoriaakash** [comment]
Added app icon in #30

**Comment by Aniket762** [comment]
> Change the app icon from flutter default to the "achieve" logo.

Do add the application name and name it `Achieve`. Do attach a screenshot of how the app icon looks on your mobile device or emulator!

**Comment by rajoriaakash** [comment]
> > Change the app icon from flutter default to the "achieve" logo.
> 
> Do add the application name and name it `Achieve`. Do attach a screenshot of how the app icon looks on your mobile device or emulator!

Alright, Did it!
