### ISSUE TITLE
Add a logo 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#6]
A logo similar to this https://github.com/betaoverflow/donna , you may either create it on your own or get a logo from the internet which has a creative license. 

Briefing about the app will help students find opportunities, get resume reviews done, and course materials. Something along the lines would work.

Before sending the PR reply over here with logo if approved send the PR

**Comment by Neeraj2002** [comment]
I would like to make the logo!

**Comment by Aniket762** [comment]
Sure @Neeraj2002 go for it. Remember to send the logo here before the PR

**Comment by Neeraj2002** [comment]
I found this logo, Hope you like it! @Aniket762 
[https://res.cloudinary.com/dnnaacqq0/image/upload/v1633155625/image_6_zrgibx.png](url)

Just copy and paste the link!

**Comment by Rishavgupta12345** [comment]
can i work on this issue

**Comment by Aniket762** [comment]
@Rishavgupta12345 go for it

**Comment by Rishavgupta12345** [comment]
@Aniket762  bro i looked into your code its not a application . this is just a framework . you can't make logo  icon of it

**Comment by Aniket762** [comment]
Hey, @Rishavgupta12345 actually we are starting out to build the application, we have just created the repo yesterday. The plan was according to the logo deciding the color palette for the application! 

Let me brief you on what we are building: 
A mobile application in which users get notified whenever a new opportunity drops in (for example SDE intern at Google applications are open) + A roadmap for various courses with links to several free resources trackwise + an option to get mentor support for resume review, interview tips, and guidance. 

Hope this clears on what is the application we are trying to build!

**Comment by Rishavgupta12345** [comment]
i wont make a icon i am not a photoshop person . but I can drop some images from google which can be the required icon .

i was just going to select a icon from google and install it in your code that's it .
if you have a icon png which you required then tell me I will do it in your code

https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.pngitem.com%2Fpimgs%2Fm%2F361-3612724_coding-icons-hd-png-download.png&imgrefurl=https%3A%2F%2Fwww.pngitem.com%2Fmiddle%2Fhiobbbx_coding-icons-hd-png-download%2F&tbnid=WLQhw4ZlBMn62M&vet=12ahUKEwjVjsH4uavzAhUknEsFHQicBPUQMyhiegUIARCeAQ..i&docid=Qx6pVgaI64oGSM&w=860&h=765&q=coding%20app%20icon%20png&ved=2ahUKEwjVjsH4uavzAhUknEsFHQicBPUQMyhiegUIARCeAQ

**Comment by aabhas-sao** [comment]
@Aniket762 If previous logos are not finalized I would like to give this a shot.

**Comment by Aniket762** [comment]
> i wont make a icon i am not a photoshop person . but I can drop some images from google which can be the required icon .
> 
> i was just going to select a icon from google and install it in your code that's it . if you have a icon png which you required then tell me I will do it in your code
> 
> https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.pngitem.com%2Fpimgs%2Fm%2F361-3612724_coding-icons-hd-png-download.png&imgrefurl=https%3A%2F%2Fwww.pngitem.com%2Fmiddle%2Fhiobbbx_coding-icons-hd-png-download%2F&tbnid=WLQhw4ZlBMn62M&vet=12ahUKEwjVjsH4uavzAhUknEsFHQicBPUQMyhiegUIARCeAQ..i&docid=Qx6pVgaI64oGSM&w=860&h=765&q=coding%20app%20icon%20png&ved=2ahUKEwjVjsH4uavzAhUknEsFHQicBPUQMyhiegUIARCeAQ

@Rishavgupta12345 thanks for the suggestion, but the motive behind this beginner-friendly issue was to promote designer's contribute, it was more like take inspiration from what is available on the internet and modify using design saas. It's better for us to assign to someone who is a designer. We would be creating more dev and docs issues you can keep an eye on it. I am unassigning it to you .

**Comment by Aniket762** [comment]
> @Aniket762 If previous logos are not finalized I would like to give this a shot.

Sure thing @aabhas-sao

**Comment by aabhas-sao** [comment]
![achieve](https://user-images.githubusercontent.com/58210877/135745727-42adf62a-eb59-43d2-983e-92fec4d319c6.jpg)
@Aniket762 how about this one. Would you like to change the color scheme.

**Comment by Aniket762** [comment]
> ![achieve](https://user-images.githubusercontent.com/58210877/135745727-42adf62a-eb59-43d2-983e-92fec4d319c6.jpg) @Aniket762 how about this one. Would you like to change the color scheme?

Looks good to me. Just remove the bg and send the PR. Add the logo in `assets`
