### ISSUE TITLE
Add PWA support to Gatsby 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/achieve#8]
In the client folder, you can find the Gatsby starter add PWA support to it! 

Refer: https://www.digitalocean.com/community/tutorials/gatsbyjs-gatsby-pwa

Please help us by putting a star to increase the visibility

**Comment by a-sambhab** [comment]
Hey @Aniket762 i would like to work on this can you assign me?

**Comment by Aniket762** [comment]
Sure go for it, this issue can be taken in after someone has solved https://github.com/betaoverflow/achieve/issues/7 so would be great if you can take this in.

**Comment by a-sambhab** [comment]
yeah sure you can assign number 8 to me as well, will it be fine with just the default starter??

**Comment by Aniket762** [comment]
> yeah sure you can assign number 8 to me as well, will it be fine with just the default starter??

Yes that would do, all you need to do is comment in the issue so that I can assign both of you!
